@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@version = api/v1
@contentType = application/json

###
GET http://{{host}}/{{version}}/players
Content-Type: {{contentType}}

###

GET http://{{host}}/{{version}}/players/4
Content-Type: {{contentType}}

###

DELETE http://{{host}}/{{version}}/players/3
Content-Type: {{contentType}}
