@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}/players
Content-Type: {{contentType}}

###

GET http://{{host}}/players/2
Content-Type: {{contentType}}
