@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@version = api/v1
@contentType = application/json

###
GET http://{{host}}/{{version}}/tournaments
Content-Type: {{contentType}}

###

GET http://{{host}}/{{version}}/tournaments/2
Content-Type: {{contentType}}

###

POST http://{{host}}/{{version}}/tournaments
Content-Type: {{contentType}}

{
  "name": "Hawaii Invitational",
  "description": "A prestigious golf tournament held in Hawaii.",
  "status": "upcoming",
  "startDate": "2026-01-10",
  "endDate": "2026-01-15"
}

###
DELETE http://{{host}}/{{version}}/tournaments/3
Content-Type: {{contentType}}
